# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gps.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_gpswindow(object):
    def openWindowBicicletas(self):
        from bicicletas import Ui_bicicletawindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_bicicletawindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openWindowVentas(self):
        from ventas import Ui_ventaswindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ventaswindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, gpswindow):
        gpswindow.setObjectName("gpswindow")
        gpswindow.resize(931, 751)
        gpswindow.setStyleSheet("background-color: rgb(214, 230, 245);")
        self.centralwidget = QtWidgets.QWidget(gpswindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalToolBox = QtWidgets.QToolBox(self.centralwidget)
        self.verticalToolBox.setGeometry(QtCore.QRect(0, -10, 181, 721))
        self.verticalToolBox.setStyleSheet("background-color: rgb(146, 168, 191);")
        self.verticalToolBox.setObjectName("verticalToolBox")
        self.verticalToolBoxPage1 = QtWidgets.QWidget()
        self.verticalToolBoxPage1.setGeometry(QtCore.QRect(0, 0, 181, 694))
        self.verticalToolBoxPage1.setObjectName("verticalToolBoxPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalToolBoxPage1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnbicicletas3 = QtWidgets.QPushButton(self.verticalToolBoxPage1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnbicicletas3.setFont(font)
        self.btnbicicletas3.setStyleSheet("background-color: rgb(233, 238, 242);")
        self.btnbicicletas3.setObjectName("btnbicicletas3")
        self.btnbicicletas3.clicked.connect(lambda: self.openWindowBicicletas())
        self.btnbicicletas3.clicked.connect(gpswindow.close)
        self.verticalLayout.addWidget(self.btnbicicletas3)
        self.btnventas3 = QtWidgets.QPushButton(self.verticalToolBoxPage1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnventas3.setFont(font)
        self.btnventas3.setStyleSheet("background-color: rgb(233, 238, 242);")
        self.btnventas3.setObjectName("btnventas3")
        self.btnventas3.clicked.connect(lambda: self.openWindowVentas())
        self.btnventas3.clicked.connect(gpswindow.close)
        self.verticalLayout.addWidget(self.btnventas3)
        self.verticalToolBox.addItem(self.verticalToolBoxPage1, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 0, 751, 521))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1366_2000.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.boxid = QtWidgets.QTextEdit(self.centralwidget)
        self.boxid.setGeometry(QtCore.QRect(290, 620, 191, 31))
        self.boxid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.boxid.setObjectName("boxid")
        self.btnalarma = QtWidgets.QPushButton(self.centralwidget)
        self.btnalarma.setGeometry(QtCore.QRect(600, 582, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnalarma.setFont(font)
        self.btnalarma.setStyleSheet("background-color: rgb(233, 238, 242);")
        self.btnalarma.setObjectName("btnalarma")
        self.btnbuscar = QtWidgets.QPushButton(self.centralwidget)
        self.btnbuscar.setGeometry(QtCore.QRect(600, 640, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnbuscar.setFont(font)
        self.btnbuscar.setStyleSheet("background-color: rgb(233, 238, 242);")
        self.btnbuscar.setObjectName("btnbuscar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 590, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.verticalToolBox.raise_()
        self.boxid.raise_()
        self.btnalarma.raise_()
        self.btnbuscar.raise_()
        self.label_2.raise_()
        gpswindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(gpswindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 931, 21))
        self.menubar.setObjectName("menubar")
        gpswindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(gpswindow)
        self.statusbar.setObjectName("statusbar")
        gpswindow.setStatusBar(self.statusbar)

        self.retranslateUi(gpswindow)
        QtCore.QMetaObject.connectSlotsByName(gpswindow)

    def retranslateUi(self, gpswindow):
        _translate = QtCore.QCoreApplication.translate
        gpswindow.setWindowTitle(_translate("gpswindow", "gpswindow"))
        self.btnbicicletas3.setText(_translate("gpswindow", "Bicicletas"))
        self.btnventas3.setText(_translate("gpswindow", "Ventas"))
        self.btnalarma.setText(_translate("gpswindow", "Activar Alarma"))
        self.btnbuscar.setText(_translate("gpswindow", "Buscar"))
        self.label_2.setText(_translate("gpswindow", "Insertar ID"))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    gpswindow = QtWidgets.QMainWindow()
    ui = Ui_gpswindow()
    ui.setupUi(gpswindow)
    gpswindow.show()
    sys.exit(app.exec_())
