# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iniciosesion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mysql.connector import Error
import mysql.connector

userslist = []
passwordslist = []
newdicc = {}
n = 0
try:
    cnx = mysql.connector.connect(user='root', password='0keRyWzSUw',
                                host='127.0.0.1',
                                database='BicicleTON')
    
    if cnx.is_connected():
        db_Info = cnx.get_server_info()
        print("Connected to MySQL Server version ", db_Info)
        cursor_users = cnx.cursor()
        cursor_users.execute("select usuario from usuarios;")
        users = cursor_users.fetchall()
        for x in users:
            for a in x:
                userslist.append(a) 
        cursor_users.execute("select contrasenyah from usuarios;")
        passwords = cursor_users.fetchall()
        for x in passwords:
            for a in x:
                passwordslist.append(a)
        for x in userslist:
            if (x not in newdicc):
                newdicc[x]=passwordslist[n]
                n += 1

except Error as e:
    print("Error while connecting to MySQL", e)

cnx.close()

class Ui_sesionwindow(object):
    def openWindowInicio(self):
        nombre = self.boxusuario.toPlainText()
        contrasenia = self.boxcontrasenia.toPlainText()
        diccionario={}
        diccionario[nombre]=contrasenia
        for key, val in newdicc.items():
            if key == nombre and val == contrasenia:
                from inicio import Ui_iniciowindow
                self.window = QtWidgets.QMainWindow()
                self.ui = Ui_iniciowindow()
                self.ui.setupUi(self.window)
                self.window.show()
                sesionwindow.close()

    def setupUi(self, sesionwindow):
        sesionwindow.setObjectName("sesionwindow")
        sesionwindow.resize(1005, 661)
        sesionwindow.setStyleSheet("background-color: rgb(214, 230, 245);")
        self.centralwidget = QtWidgets.QWidget(sesionwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, -10, 611, 651))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bicicletas-recurso.jpeg"))
        self.label.setObjectName("label")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(80, 90, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.boxusuario = QtWidgets.QTextEdit(self.centralwidget)
        self.boxusuario.setGeometry(QtCore.QRect(80, 120, 191, 31))
        self.boxusuario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.boxusuario.setObjectName("boxusuario")
        self.boxcontrasenia = QtWidgets.QTextEdit(self.centralwidget)
        self.boxcontrasenia.setGeometry(QtCore.QRect(80, 220, 191, 31))
        self.boxcontrasenia.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.boxcontrasenia.setObjectName("boxcontrasenia")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(80, 190, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.btnsesion = QtWidgets.QPushButton(self.centralwidget)
        self.btnsesion.setGeometry(QtCore.QRect(100, 290, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnsesion.setFont(font)
        self.btnsesion.setStyleSheet("background-color: rgb(233, 238, 242);")
        self.btnsesion.setObjectName("btnsesion")
        self.btnsesion.clicked.connect(lambda: self.openWindowInicio())
        sesionwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(sesionwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1005, 21))
        self.menubar.setObjectName("menubar")
        sesionwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sesionwindow)
        self.statusbar.setObjectName("statusbar")
        sesionwindow.setStatusBar(self.statusbar)

        self.retranslateUi(sesionwindow)
        QtCore.QMetaObject.connectSlotsByName(sesionwindow)

    def retranslateUi(self, sesionwindow):
        _translate = QtCore.QCoreApplication.translate
        sesionwindow.setWindowTitle(_translate("sesionwindow", "sesionwindow"))
        self.label1.setText(_translate("sesionwindow", "Nombre de usuario"))
        self.label2.setText(_translate("sesionwindow", "Contraseña"))
        self.btnsesion.setText(_translate("sesionwindow", "Iniciar Sesión"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sesionwindow = QtWidgets.QMainWindow()
    ui = Ui_sesionwindow()
    ui.setupUi(sesionwindow)
    sesionwindow.show()
    sys.exit(app.exec_())
