# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_iniciowindow(object):
    def openWindowBicicletas(self):
        from bicicletas import Ui_bicicletawindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_bicicletawindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openWindowGPS(self):
        from gps import Ui_gpswindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_gpswindow()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def openWindowVentas(self):
        from ventas import Ui_ventaswindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ventaswindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, iniciowindow):
        iniciowindow.setObjectName("iniciowindow")
        iniciowindow.setEnabled(True)
        iniciowindow.resize(860, 715)
        iniciowindow.setStyleSheet("background-color: rgb(214, 230, 245);")
        self.centralwidget = QtWidgets.QWidget(iniciowindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(180, 0, 681, 671))
        self.label3.setText("")
        self.label3.setPixmap(QtGui.QPixmap("../../../Pictures/bicicleta.jpg"))
        self.label3.setScaledContents(True)
        self.label3.setObjectName("label3")
        self.toolbox1 = QtWidgets.QToolBox(self.centralwidget)
        self.toolbox1.setGeometry(QtCore.QRect(0, -20, 181, 711))
        self.toolbox1.setStyleSheet("background-color: rgb(146, 168, 191);")
        self.toolbox1.setObjectName("toolbox1")
        self.verticalToolBoxPage1 = QtWidgets.QWidget()
        self.verticalToolBoxPage1.setGeometry(QtCore.QRect(0, 0, 181, 684))
        self.verticalToolBoxPage1.setObjectName("verticalToolBoxPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalToolBoxPage1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnbicicletas = QtWidgets.QPushButton(self.verticalToolBoxPage1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnbicicletas.setFont(font)
        self.btnbicicletas.setStyleSheet("background-color: rgb(233, 238, 242);")
        self.btnbicicletas.setObjectName("btnbicicletas")
        self.btnbicicletas.clicked.connect(lambda: self.openWindowBicicletas())
        self.btnbicicletas.clicked.connect(iniciowindow.close)
        self.verticalLayout.addWidget(self.btnbicicletas)
        self.btnventas = QtWidgets.QPushButton(self.verticalToolBoxPage1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnventas.setFont(font)
        self.btnventas.setStyleSheet("background-color: rgb(233, 238, 242);")
        self.btnventas.setObjectName("btnventas")
        self.btnventas.clicked.connect(lambda: self.openWindowVentas())
        self.btnventas.clicked.connect(iniciowindow.close)
        self.verticalLayout.addWidget(self.btnventas)
        self.btngps = QtWidgets.QPushButton(self.verticalToolBoxPage1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btngps.setFont(font)
        self.btngps.setStyleSheet("background-color: rgb(233, 238, 242);")
        self.btngps.setObjectName("btngps")
        self.btngps.clicked.connect(lambda: self.openWindowGPS())
        self.btngps.clicked.connect(iniciowindow.close)
        self.verticalLayout.addWidget(self.btngps)
        self.toolbox1.addItem(self.verticalToolBoxPage1, "")
        iniciowindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(iniciowindow)
        self.statusbar.setObjectName("statusbar")
        iniciowindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(iniciowindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 860, 21))
        self.menuBar.setObjectName("menuBar")
        iniciowindow.setMenuBar(self.menuBar)
        self.actionVerTabla = QtWidgets.QAction(iniciowindow)
        self.actionVerTabla.setObjectName("actionVerTabla")

        self.retranslateUi(iniciowindow)
        QtCore.QMetaObject.connectSlotsByName(iniciowindow)

    def retranslateUi(self, iniciowindow):
        _translate = QtCore.QCoreApplication.translate
        iniciowindow.setWindowTitle(_translate("iniciowindow", "iniciowindow"))
        self.btnbicicletas.setText(_translate("iniciowindow", "Bicicletas"))
        self.btnventas.setText(_translate("iniciowindow", "Ventas"))
        self.btngps.setText(_translate("iniciowindow", "GPS"))
        self.actionVerTabla.setText(_translate("iniciowindow", "VerTabla"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    iniciowindow = QtWidgets.QMainWindow()
    ui = Ui_iniciowindow()
    ui.setupUi(iniciowindow)
    iniciowindow.show()
    sys.exit(app.exec_())
